In [1]:
import torch

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [3]:
# making a tensor by specifying the shape
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[2.9427e-44, 0.0000e+00, 1.7334e-33],
        [6.1153e-36, 3.8376e-34, 3.9300e-31]])


In [4]:
# uniform random distribution, values between [0,1)
describe(torch.rand(2,3))

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[0.5360, 0.6527, 0.2329],
        [0.9430, 0.5131, 0.0646]])


In [5]:
# random normal distribution
describe(torch.randn(2,3))

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[-1.4131, -0.9354,  0.4924],
        [-0.4260, -0.0760,  1.7063]])


In [6]:
# pytorch functions with _ indicate inplace
describe(torch.zeros(2,3))

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones(2,3)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x.fill_(7)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[7., 7., 7.],
        [7., 7., 7.]])


In [9]:
# creating tensors using python lists
x = torch.Tensor([[1,2,3],
                  [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
import numpy as np

In [11]:
npy = np.random.randn(2,3)
npy

array([[ 0.84814093, -0.50127062,  1.7176989 ],
       [-0.65516516, -0.0460408 ,  1.0118112 ]])

In [12]:
npy.dtype

dtype('float64')

In [13]:
# notice that the data type is DoubleTensor instead of the default float tensor
# this corresponds to numpys float64 representation
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[ 0.8481, -0.5013,  1.7177],
        [-0.6552, -0.0460,  1.0118]], dtype=torch.float64)


In [14]:
# we can specify the data type of a tensor during initialization
x = torch.tensor([[1,2,3],
                  [4,5,6]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
# we can also convert it from one data type to another later
x = torch.Tensor([[1,2,3],
                  [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [16]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [17]:
x.size()

torch.Size([2, 3])

In [18]:
x = torch.randn(2,3)

In [19]:
describe(x+x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[-0.2272, -5.9033, -2.9113],
        [ 1.9108,  2.3741, -2.2889]])


In [20]:
# rows are dimension 0 i.e if we do torch.sum(x, dim = 0)
# it'll add all rows together
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [21]:
x = x.view(2,3)
describe(x)

Type: torch.LongTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [22]:
describe(torch.sum(x, dim=0))

Type: torch.LongTensor
Shape: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [23]:
describe(torch.sum(x, dim=1))

Type: torch.LongTensor
Shape: torch.Size([2])
Values: 
tensor([ 3, 12])


In [24]:
describe(torch.transpose(x, 0, 1))

Type: torch.LongTensor
Shape: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [25]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [26]:
describe(x[:1,:2])

Type: torch.LongTensor
Shape: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [27]:
describe(x[0,1])

Type: torch.LongTensor
Shape: torch.Size([])
Values: 
1


In [28]:
# ?torch.index_select

In [29]:
# noncontiguous indexing - indexing along rows and cols using indices
# eg if indices are [1,3,7] along rows then select rows 1,3 and 7
# requirement: indices have to be LongTensors
indices = torch.LongTensor([0,2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [30]:
# selecting the first row twice
indices = torch.LongTensor([0,0])
describe(torch.index_select(x, 0, indices))

Type: torch.LongTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [31]:
# 0th row 0th value
# 1st row 2nd value
row_indices = torch.arange(2).long() # [0,1]
col_indices = torch.LongTensor([0,2])
describe(x[row_indices,col_indices])

Type: torch.LongTensor
Shape: torch.Size([2])
Values: 
tensor([0, 5])


In [32]:
describe(torch.cat([x,x], dim=0))

Type: torch.LongTensor
Shape: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [33]:
describe(torch.cat([x,x], dim = 1))

Type: torch.LongTensor
Shape: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [34]:
describe(torch.stack([x,x], dim = 0))

Type: torch.LongTensor
Shape: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [35]:
x1 = torch.arange(6).view(2,3)
describe(x1)

Type: torch.LongTensor
Shape: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [36]:
x2 = torch.ones(3,2).long()
x2

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [37]:
x2[:,1] += 1
describe(x2)

Type: torch.LongTensor
Shape: torch.Size([3, 2])
Values: 
tensor([[1, 2],
        [1, 2],
        [1, 2]])


In [38]:
# mm expects long tensors
describe(torch.mm(x1, x2))

Type: torch.LongTensor
Shape: torch.Size([2, 2])
Values: 
tensor([[ 3,  6],
        [12, 24]])


In [39]:
x = torch.ones(2,2, requires_grad = True)

In [40]:
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [41]:
print(x.grad is None)

True


In [42]:
y = (x + 2) * (x + 5) + 3
describe(y)

Type: torch.FloatTensor
Shape: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)


In [43]:
print(x.grad is None)

True


In [44]:
z = y.mean()
describe(z)

Type: torch.FloatTensor
Shape: torch.Size([])
Values: 
21.0


In [45]:
z.backward()
print(x.grad is None)

False


In [46]:
x.grad

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])

In [47]:
# access to gpus is via an api called CUDA (invented by NVDIA)
print(torch.cuda.is_available())

True


In [48]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [49]:
x = torch.rand(3,3).to(device)
describe(x)

Type: torch.cuda.FloatTensor
Shape: torch.Size([3, 3])
Values: 
tensor([[0.2555, 0.1106, 0.5127],
        [0.7979, 0.1350, 0.5040],
        [0.7489, 0.4700, 0.6185]], device='cuda:0')


In [50]:
# to operate on cuda and non cuda objects we need to make sure they are on the same device
# otherwise things can break
y = torch.rand(3,3)

# this will break
# x + y

In [51]:
cpu_device = torch.device("cpu")
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

tensor([[0.8260, 0.8455, 0.9440],
        [1.5135, 1.0017, 0.6802],
        [1.3883, 0.8983, 1.5916]])

In [52]:
# exercises
# 1. create a 2d tensor and add a dimension of size 1 inserted at dim 0

x = torch.randn(2,2)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 2])
Values: 
tensor([[-0.0586,  0.2595],
        [-1.7208, -0.8205]])


In [53]:
x = x[None]
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([1, 2, 2])
Values: 
tensor([[[-0.0586,  0.2595],
         [-1.7208, -0.8205]]])


In [54]:
# 2. remove the dimension you added in the previous tensor
x = x.squeeze(0)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 2])
Values: 
tensor([[-0.0586,  0.2595],
        [-1.7208, -0.8205]])


In [55]:
# random tensor of shape 5,3 in the range [3,7)
torch.rand(5,3).uniform_(3,7)

tensor([[4.6660, 3.7595, 6.6199],
        [3.4449, 3.8279, 4.2461],
        [5.5295, 5.6477, 4.9315],
        [4.9041, 5.9927, 3.1219],
        [4.4873, 4.8302, 4.7676]])

In [56]:
# create a tensor with values from the normal distribution
torch.randn(2,2)

tensor([[ 1.5176, -0.9821],
        [ 0.6098, -0.4849]])

In [57]:
# retreive indices of all non zero elements in the tensor
x = torch.Tensor([1,1,1,0,1])
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([5])
Values: 
tensor([1., 1., 1., 0., 1.])


In [58]:
torch.nonzero(x)

tensor([[0],
        [1],
        [2],
        [4]])

In [59]:
# create a random tensor of size (3,1) and then horizontally stack 4 copies
x = torch.rand(3,1)
x.expand(3,4)
# describe(torch.cat([x] * 4, dim = 1))

tensor([[0.5939, 0.5939, 0.5939, 0.5939],
        [0.2302, 0.2302, 0.2302, 0.2302],
        [0.7918, 0.7918, 0.7918, 0.7918]])

In [60]:
# batch matrix matrix product of 2, 3 dimensional matrices
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)

torch.bmm(a,b)

tensor([[[1.9470, 1.5140, 2.0880, 1.1435],
         [1.8199, 1.7963, 2.2495, 1.3375],
         [1.2912, 1.8078, 2.2660, 1.2727],
         [1.6453, 2.3223, 2.5440, 1.1613]],

        [[0.6478, 1.0042, 0.7042, 0.9162],
         [1.2754, 1.8217, 1.2953, 1.3332],
         [0.6605, 0.7519, 0.6729, 0.4231],
         [1.4140, 1.5477, 1.1877, 1.4355]],

        [[0.4628, 0.8480, 0.8132, 0.3131],
         [0.7011, 1.4638, 1.5294, 1.5334],
         [1.1789, 1.6895, 1.4924, 1.1091],
         [0.6814, 1.0022, 1.3146, 1.2103]]])

In [61]:
b = torch.rand(5,4)
# b.unsqueeze(0) - add a unit dim at the start
# .expand(a.size(0), *b.size()) - expand it to a's shape
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), * b.size()))

tensor([[[1.6024, 1.7192, 1.8889, 0.7813],
         [1.6210, 1.8735, 1.8281, 0.8064],
         [1.6264, 1.8551, 1.5052, 0.6422],
         [2.0936, 1.8515, 2.0803, 0.8288]],

        [[0.9868, 0.7031, 1.0160, 0.2782],
         [1.5652, 1.4492, 1.7810, 0.7083],
         [0.9190, 0.8217, 0.8532, 0.5067],
         [1.2528, 1.5955, 1.4243, 0.7108]],

        [[1.4571, 0.9733, 1.5042, 0.4019],
         [1.5340, 1.9290, 1.2638, 0.8944],
         [1.7605, 1.9412, 1.7742, 0.7774],
         [1.2567, 1.4694, 1.3190, 0.7680]]])